### PR TITLE
Remove web. Rewrite to use openmicroscopy/omero-server

### PR DESCRIPTION
**Pull request by manics**
Rewrites omero-grid to use https://github.com/openmicroscopy/omero-server-docker
There are separate master and slave images, and the omero-web image is removed.

The test scripts are identical to those in https://github.com/openmicroscopy/omero-server-docker/pull/1 with the exception of `test.sh` which has to orcehstrates the slave images.

--depends-on https://github.com/openmicroscopy/omero-server-docker/pull/1
--on-hold
--exclude
To test this you will need to change `FROM test-omero-server` in `{master,slave}/Dockerfile` to an image with https://github.com/openmicroscopy/omero-server-docker/pull/1

### CODE REVIEW

**Comment by joshmoore** [comment]
Just for clarity, I assume the target here is `0.2.0` ?

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [DOCKER-merge#22](https://ci.openmicroscopy.org/job/DOCKER-merge/22/). See the [console output](https://ci.openmicroscopy.org/job/DOCKER-merge/22/consoleText) for more details.
Possible conflicts:
  - PR #8 dpwrussell 'Streamline omero-grid build and add OMEROPASS variable for entrypoint'
    - omero-grid-web/Dockerfile
    - omero-grid/run.sh
    - omero-grid-web/run.sh
    - README.md
    - omero-grid/Dockerfile

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [DOCKER-merge#23](https://ci.openmicroscopy.org/job/DOCKER-merge/23/). See the [console output](https://ci.openmicroscopy.org/job/DOCKER-merge/23/consoleText) for more details.
Possible conflicts:
  - PR #8 dpwrussell 'Streamline omero-grid build and add OMEROPASS variable for entrypoint'
    - omero-grid-web/Dockerfile
    - omero-grid/run.sh
    - omero-grid-web/run.sh
    - README.md
    - omero-grid/Dockerfile

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [DOCKER-merge#24](https://ci.openmicroscopy.org/job/DOCKER-merge/24/). See the [console output](https://ci.openmicroscopy.org/job/DOCKER-merge/24/consoleText) for more details.
Possible conflicts:
  - PR #8 dpwrussell 'Streamline omero-grid build and add OMEROPASS variable for entrypoint'
    - omero-grid-web/Dockerfile
    - omero-grid/run.sh
    - omero-grid-web/run.sh
    - README.md
    - omero-grid/Dockerfile

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [DOCKER-merge#25](https://ci.openmicroscopy.org/job/DOCKER-merge/25/). See the [console output](https://ci.openmicroscopy.org/job/DOCKER-merge/25/consoleText) for more details.
Possible conflicts:
  - PR #8 dpwrussell 'Streamline omero-grid build and add OMEROPASS variable for entrypoint'
    - omero-grid-web/Dockerfile
    - omero-grid/run.sh
    - omero-grid-web/run.sh
    - README.md
    - omero-grid/Dockerfile

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [DOCKER-merge#26](https://ci.openmicroscopy.org/job/DOCKER-merge/26/). See the [console output](https://ci.openmicroscopy.org/job/DOCKER-merge/26/consoleText) for more details.
Possible conflicts:
  - PR #8 dpwrussell 'Streamline omero-grid build and add OMEROPASS variable for entrypoint'
    - omero-grid-web/Dockerfile
    - omero-grid/run.sh
    - omero-grid-web/run.sh
    - README.md
    - omero-grid/Dockerfile

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [DOCKER-merge#27](https://ci.openmicroscopy.org/job/DOCKER-merge/27/). See the [console output](https://ci.openmicroscopy.org/job/DOCKER-merge/27/consoleText) for more details.
Possible conflicts:
  - PR #8 dpwrussell 'Streamline omero-grid build and add OMEROPASS variable for entrypoint'
    - omero-grid-web/Dockerfile
    - omero-grid/run.sh
    - omero-grid-web/run.sh
    - README.md
    - omero-grid/Dockerfile

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [DOCKER-merge#28](https://ci.openmicroscopy.org/job/DOCKER-merge/28/). See the [console output](https://ci.openmicroscopy.org/job/DOCKER-merge/28/consoleText) for more details.
Possible conflicts:
  - PR #8 dpwrussell 'Streamline omero-grid build and add OMEROPASS variable for entrypoint'
    - omero-grid-web/Dockerfile
    - omero-grid/run.sh
    - omero-grid-web/run.sh
    - README.md
    - omero-grid/Dockerfile

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [DOCKER-merge#29](https://ci.openmicroscopy.org/job/DOCKER-merge/29/). See the [console output](https://ci.openmicroscopy.org/job/DOCKER-merge/29/consoleText) for more details.
Possible conflicts:
  - PR #8 dpwrussell 'Streamline omero-grid build and add OMEROPASS variable for entrypoint'
    - omero-grid-web/Dockerfile
    - omero-grid/run.sh
    - omero-grid-web/run.sh
    - README.md
    - omero-grid/Dockerfile

**Comment by joshmoore** [comment]
@manics: what's the way forward here?

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [DOCKER-merge#126](https://ci.openmicroscopy.org/job/DOCKER-merge/126/). See the [console output](https://ci.openmicroscopy.org/job/DOCKER-merge/126/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - omero-grid-web/requirements.yml
    - omero-grid/requirements.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [DOCKER-merge#127](https://ci.openmicroscopy.org/job/DOCKER-merge/127/). See the [console output](https://ci.openmicroscopy.org/job/DOCKER-merge/127/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - omero-grid-web/requirements.yml
    - omero-grid/requirements.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [DOCKER-merge#128](https://ci.openmicroscopy.org/job/DOCKER-merge/128/). See the [console output](https://ci.openmicroscopy.org/job/DOCKER-merge/128/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - omero-grid-web/requirements.yml
    - omero-grid/requirements.yml

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [DOCKER-merge#129](https://ci.openmicroscopy.org/job/DOCKER-merge/129/). See the [console output](https://ci.openmicroscopy.org/job/DOCKER-merge/129/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - omero-grid-web/requirements.yml
    - omero-grid/requirements.yml

**Pull request closed without merging**
