### PR TITLE
Add travis

### PR DESCRIPTION
**Pull request by atarkowska**
took me a while, but 

```
cd ome-docker/
PATHS_TO_KEEP=".travis.yml" 
git filter-branch -f --index-filter "git rm --ignore-unmatch --cached -qr -- . && git reset -q \$GIT_COMMIT -- $PATHS_TO_KEEP" --prune-empty -- HEAD
git remote add travis git@github.com:aleksandra-tarkowska/omero-grid-docker.git
git push travis HEAD:refs/heads/travis

cd ../omero-grid-docker/
git fetch --all
git reset --hard origin/master
git checkout -b add_travis ola/travis
git rebase origin/master
git push ola add_travis
```

### CODE REVIEW

**Comment by atarkowska** [comment]
unfortunately I cannot run them at the moment, as `omero-grid-test-master` is crashing in the middle of startup and web is not even starting, need to investigate it

**Comment by atarkowska** [comment]
travis is failing on https://travis-ci.org/openmicroscopy/omero-grid-docker/builds/127877699#L2679 exactly the same as in the original repo https://travis-ci.org/ome/ome-docker/builds/127249792#L2685

**Comment by joshmoore** [comment]
Looks like clean:

```
+docker rm -f -v omero-grid-test-db omero-grid-test-master omero-grid-test-slave-1 omero-grid-test-web
```

is getting called twice.

**Comment by atarkowska** [comment]
how is that related? it cleans up before `build.py` and after `test_login.sh` that cannot connect to web.

**Comment by atarkowska** [comment]
maybe @manics could guide how to start them manually ;-)

**Comment by manics** [comment]
Maybe gunicorn is too old? https://github.com/openmicroscopy/omero-grid-docker/blob/master/omero-grid-web/Dockerfile#L15

**Comment by manics** [comment]
@aleksandra-tarkowska do the instructions in the README work?

**Comment by atarkowska** [comment]
that is definitely true as yum will install python-gunicorn-18.0-2.el7.noarch. The problem locally is that readme doesn't work, see https://gist.github.com/aleksandra-tarkowska/0610494b668c64abe1c2f5257325a7d9.

**Comment by joshmoore** [comment]
Anything to revive here once gh-2 is merged?

**Pull request closed without merging**
